### ISSUE TITLE
Openjdk 8 Support

### ISSUE THREAD

**Issue by siriux** [alexkasko/openjdk-unofficial-builds#17] opened 2014-01-21 08:47 UTC
Do you plan to add Openjdk 8 support ?

If so, it would be interesting for me to have an option for Small VM.
http://openjdk.java.net/jeps/148

Thanks,
Pablo

**Comment by alexkasko** [comment] 2015-01-03 15:53
Hi

On 12/23/2014 02:50 PM, Scott Will Moore wrote:
> Hi,
> With Java 9 on the horizon do you think we will be seeing an openjdk 8 unoffical build soon?

Yes, java moving faster now then some years ago. As java 8 is less then 
one year old this situation is quite unusual in java world, where java 6 
ruled for almost 6 years.

The current plan is to release jdk8 builds without installers on linux 
and mac (and probably without debug builds - they and installers can be 
added later). I won't do any promises about dates, though.

> I help out the opensource project (scoop)[http://scoop.sh/] and it relies on pre-built binaries to use and install. It currently uses your Java 7 binaries as an open source alternative to the oracle jdk, otherwise how hard would you think it would be for me to create and distribute a windows openjdk binary myself?

With jdk8 the build process became easy even on windows. The only 
problem on windows can be FreeType libs, but you can get prebuilt 
binaries from openjdk7 branch of this repo.

>
> Thanks, Scott
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/alexkasko/openjdk-unofficial-builds/issues/17#issuecomment-67957931
>


-- 
-Alex

**Comment by scottwillmoore** [comment] 2015-01-04 04:05
Thank you for the update. As for [scoop](http://scoop.sh/) only a windows build is actually required, and does not require an installer, but just a extractable zip. So it would be fantastic if JDK builds could be released soon. :smile:

Otherwise I just had a brief look at building the JDK manually and it appears to be rather simple, with the main issues lying in installing the dependencies. I believe however that it will be much safer to include the JDK built by you as it is used by many others, and can be well tested.

Anyway, thanks for the update.

**Comment by gouessej** [comment] 2015-01-04 11:23
@alexkasko Please can you indicate whether your builds will support JavaFX/OpenJFX on all platforms? Do you plan to include the OpenGL ES 2 backend for Windows too? Maybe this comment can help a bit:
https://jogamp.org/bugzilla/show_bug.cgi?id=607#c19

Do you need some help for mirroring? Sometimes it is impossible to download your builds. Thank you very much for the good work :)

**Comment by alexkasko** [comment] 2015-01-04 12:36
Hi,

On 01/04/2015 11:23 AM, Julien Gouesse wrote:
> @alexkasko Please can you indicate whether your builds will support JavaFX/OpenJFX on all platforms? Do you plan to include the OpenGL ES 2 backend for Windows too? Maybe this comment can help a bit:
> https://jogamp.org/bugzilla/show_bug.cgi?id=607#c19

Not going to include OpenJFX and additional libs, it can be useful, but 
I will try to keep these builds as close to vanilla OpenJDK as possible. 
Currently only essential things (cacerts and fonts) are added.

>
> Do you need some help for mirroring? Sometimes it is impossible to download your builds.

I am not sure here, all the downloads are served from bitbucket (except 
the very first version that was uploaded to github) and should be quite 
stable. As the checksums are stored in repo on github I think it is 
quite safe to have mirrors (can add links to mirror if you'll create one).

> Thank you very much for the good work :)

Your are welcome

>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/alexkasko/openjdk-unofficial-builds/issues/17#issuecomment-68629507
>


-- 
-Alex

**Comment by gouessej** [comment] 2015-01-04 12:45
Thank you for your answers, I understand your position, you want to keep it as simple as possible.

Actually, this one is often hard to download, it stops after a few seconds:
https://bitbucket.org/alexkasko/openjdk-unofficial-builds/downloads/openjdk-1.7.0-u60-unofficial-windows-i586-image.zip

I'll see with other JogAmp contributors if they agree with storing your builds into jogamp/deployment (with full credits to you of course).

**Comment by alexkasko** [comment] 2015-01-04 13:14
On 01/04/2015 12:45 PM, Julien Gouesse wrote:
> Thank you for your answers, I understand your position, you want to keep it as simple as possible.

Yes, it is very easy to get public distribution wrong (like it was with 
virus in jdk6 win32 builds and with broken png in IcedTea) so I'll try 
to alter (improve) these builds as little as possible.

>
> Actually, this one is often hard to download, it stops after a few seconds:
> https://bitbucket.org/alexkasko/openjdk-unofficial-builds/downloads/openjdk-1.7.0-u60-unofficial-windows-i586-image.zip

Interesting, I tried this file and download speed was unstable (varied 
from 20kbps to 1.5mbps), at least the download was successful. Maybe 
some Amazon throttling.

>
> I'll see with other JogAmp contributors if they agree with storing your builds into jogamp/deployment (with full credits to you of course).

Great, I think naming of the binaries is descriptive enough so I will be 
able to add a single link on top of README.md to the web listing of the 
mirror (instead of links to every file).

>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/alexkasko/openjdk-unofficial-builds/issues/17#issuecomment-68631644
>


-- 
-Alex

**Comment by bhavyamanasa** [comment] 2015-03-23 13:52
hi,
I am using openjdk-1.7.0-u60-unofficial-windows-amd64-installer in windows8
it is working fine for java SE, but got struck for java EE (not responding)
may i know why??

Thanks in advance.

**Comment by gouessej** [comment] 2015-03-23 14:21
@bhavyamanasa Which J2EE container do you use? You can use JVisualVM or JStack to determine where it is "stuck".

**Comment by kg5000** [comment] 2015-08-06 17:47
Any updates on a 32 bit OpenJDK build? I scrounged around and only see 1.6 and 1.7 builds. 

Many Thanks!

Ken

**Comment by djx314** [comment] 2015-08-06 19:01
+1

**Comment by codespotx** [comment] 2015-08-20 22:45
@kg5000 @djx314
as I commented already Oct 2014 I have the jdk 8 build up and running.
but mr kasko showed no interest in my findings...
i can upload my 1.8.0_51 (32/64) images if you like.

**Comment by codespotx** [comment] 2015-08-20 23:14
@siriux  (very late reply)
Compact Profiles (JEP 161) are not supported in windows build (this is was oracle calls "Delivered")
>$ make profiles
>Error: The Java SE 8 Compact Profiles are only implemented for Linux at this time

Small VM (JEP 148) also looks like a linux thing (libjvm.so, gcc), and they actually failed reduce the libjvm.so size accordingly (oracle calls this "Completed").

**Comment by siriux** [comment] 2015-08-21 06:08
@codespotx 

Thanks for your findings. I guess that with OpenJDK 8 I'll have to remove the things from rt.jar by hand, and keep the usual tricks I'm using on OpenJDK 7. At least they provide a list of classes that can be removed safely, so no more trial and error.

Not urgent for me, but I would love to see alex builds for OpenJDK 8 to start experimenting with it.

Cheers

**Comment by alexkasko** [comment] 2015-08-27 17:49
@kg5000 @djx314

Sorry, no updates from me, situation with jdk8 builds is still unclear.

@codespotx

Won't you mind contacting me over email about jdk8 builds?

-- 
-Alex

**Comment by codespotx** [comment] 2015-09-13 21:43
@alexkasko  you got mail.

**Comment by jimfb** [comment] 2015-12-03 05:15
@alexkasko I'll buy you a pizza if you get the java8 build out soon... please!!!

Seriously though, I think you're the only one who has a snowball's chance of making it work.  Any chance you could sit down for a few hours this week and take a look at it?

**Comment by alexkasko** [comment] 2015-12-15 20:46
Hi,

On 12/03/2015 05:15 AM, Jim wrote:
> @alexkasko I'll buy you a pizza if you get the java8 build out soon... please!!!

Not that I am opposing the idea :) , but still cannot say anything 
definitive on jdk8. And it just became actual again with jdk9 moved to 2017.

If you'll want to build a jdk8 tarball (not installer) for a single 
platform yourself, I think I will be able to give some detailed 
instructions/scripts, jdk8 made a lot of things easier. But all 
platforms, installers, debug builds and desirable regression test runs 
add some overhead.

>
> Seriously though, I think you're the only one who has a snowball's chance of making it work.  Any chance you could sit down for a few hours this week and take a look at it?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/alexkasko/openjdk-unofficial-builds/issues/17#issuecomment-161516473
>


-- 
-Alex

**Comment by IceMan81** [comment] 2015-12-16 03:56
FYI, you can get openjdk 8 build from Azul @ http://zulu.org/download/. I've been using Azul Zulu open jdk builds for a while now.

**Comment by djx314** [comment] 2015-12-16 04:10
@IceMan81 zulu just have openjdk 8 build for win 64, not for win 32. But I need to a win 32 openjdk 8 for my server.

**Comment by IceMan81** [comment] 2015-12-16 04:38
@djx314 I think I saw on their forum that if you contact them about a win 32 jdk 8 build, you can get one.

**Comment by alexkasko** [comment] 2015-12-16 12:52
On 12/16/2015 03:56 AM, Gesly George wrote:
> FYI, you can get openjdk 8 build from Azul @ http://zulu.org/download/. I've been using Azul Zulu open jdk builds for a while now.

Zulu is quite popular, but IMO it is closer to Oracle builds than to 
manual ones as their source code repo is not public (they still follow 
GPL correctly of course). Also no public bugtracker. For those who 
interested in technical details this link may be useful - 
https://groups.google.com/forum/#!msg/mechanical-sympathy/jQGahuzJKM4/ydeNt56mRYkJ 
(this is from Azul CTO but this is not a marketing speech).

>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/alexkasko/openjdk-unofficial-builds/issues/17#issuecomment-164983901
>


-- 
-Alex

**Comment by iswardasa** [comment] 2016-02-27 15:14
@IceMan81 :   32 bit azul ?  i havn't asked them.  there are still quite a bit of 32 bit machines that are out there.  after researching, it turns out that zulu intends to distribute to 32-bit architectures saying that it is on their "roadmap".  for now, voting on this ( https://support.azulsystems.com/hc/communities/public/questions/200917154-Need-for-32-bit-JDK-JRE ) feature request is recommended by them to stimulate development.

**Comment by iswardasa** [comment] 2016-02-27 15:14
developing using openjdk7 may still be attractive for those targeting older machines IMHO .

**Comment by coin3x** [comment] 2016-03-13 10:31
any ETA?

**Comment by alexkasko** [comment] 2016-03-13 11:05
Hi,

On 03/13/2016 10:31 AM, Coin wrote:
> any ETA?

There is a good chance for the windows-only release in late April/early 
May aligned with Oracle JDK updates that should be released in April. 
I'll update this issue with more info in some weeks.

>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/alexkasko/openjdk-unofficial-builds/issues/17#issuecomment-195930883
>


-- 
-Alex

**Comment by gouessej** [comment] 2016-03-13 12:02
@alexkasko Thanks, it will be better than nothing. I hope that you'll succeed in making it work for Linux and OS X too.

**Comment by desertkun** [comment] 2016-04-04 08:05
Indeed waiting for this. Thank you in advance!

**Comment by erickwill** [comment] 2016-04-04 13:45
@alexkasko Thank you very much for your nice job! Looking forward for updates to Linux, specially openjdk 8.

**Comment by desertkun** [comment] 2016-04-09 21:12
@alexkasko Would really appreciate any news about opejdk 8 builds.

**Comment by alexkasko** [comment] 2016-04-12 19:29
Hi,

On 04/09/2016 10:12 PM, desertkun wrote:
> @alexkasko Would really appreciate any news about opejdk 8 builds.

The current plan is to release jdk8 windows-x86_64 build at the end of 
the month. This build is going to be done not from upstream sources, but 
from OpenJDK sources used in RHEL 7 (that [are available through CentOS 
repos](http://ftp.redhat.com/redhat/linux/enterprise/7Server/en/os/README)). 
The goal it to have windows build as close as possible to 
java-1.8.0-openjdk from RHEL to cover the use-case "develop on Windows - 
deploy on RHEL/CentOS".

That win-x86_64 build is going to be thoroughly tested and updated once 
in three months after each [Oracle 
CPU](http://www.oracle.com/technetwork/topics/security/alerts-086861.html) 
release.

Other platforms (win-x86, macosx-x86_64, linux-x86_64, linux-arm32) for 
that build (from the same sources and using the same build scripts) may 
be added in future, but they won't be tested/updated on the same level 
as win-x86_64 one.

-- 
-Alex

**Comment by erickwill** [comment] 2016-04-12 19:42
@alexkasko Thanks for your nice work! Could you please try to advance version 1.8.0 also to linux? It would be great :)

**Comment by alexkasko** [comment] 2016-04-12 20:00
Hi,

On 04/12/2016 08:42 PM, erickwill wrote:
> @alexkasko Thanks for your nice work! Could you please try to advance version 1.8.0 also to linux? It would be great :)

You are welcome, just to collect some opinions on that point - what's 
wrong with java-1.8.0-openjdk on RHEL/CentOS/Fedora and their 
derivatives? It has the same level of updates/testing/stability as 
Oracle JDK and additionally has some nice features like using system 
tzdata. And it shouldn't be hard to use it in Docker on 
non-RHEL-flavoured distros.

Does your use-case require shipping "portable linux app" with jre 
included (so neither docker nor "yum install java-1.8.0-openjdk" are 
possible)?


-- 
-Alex

**Comment by erickwill** [comment] 2016-04-12 20:09
@alexkasko 
I use it under Arch Linux to build Android AOSP.
Your builds seems to work faster to build AOSP, besides I prefer to know exactly what is installed plus where is it installed, what it doesn't happen when I install the one available at the repository. For this main reason I pick your builds.

**Comment by alexkasko** [comment] 2016-04-13 10:24
Hi,

On 04/12/2016 09:09 PM, erickwill wrote:
>   @alexkasko
> I use it under Arch Linux to build Android AOSP.

Thanks for the details, that is useful to understand user needs better.

> Your builds seems to work faster to build AOSP,

I can assure you that wasn't intentional :) . I mean all openjdk-based 
builds for x86_64 have more or less the same performance characteristics 
(as VM impl is the same). And newer (jdk8 vs jdk7) builds are generally 
slightly faster than older ones.

> besides I prefer to know exactly what is installed plus where is it installed, what it doesn't happen when I install the one available at the repository. For this main reason I pick your builds.

On Linux, have you considered using something like:

dnf builddep java-1.8.0-openjdk # just the Arch flavour of it instead of 
fedora one
hg clone http://hg.openjdk.java.net/jdk8u/jdk8u/
cd jdk8u
./get_source.sh
bash ./make/scripts/hgforest.sh checkout <latest_stable_tag>
bash ./configure
make images
cp -a build/linux-x86_64-normal-server-release/images/j2sdk-image 
path/to/my/jdk

After that the only bit you may require to change it to update empty 
cacerts file in jre/lib/security/cacerts. That is generally how the 
Linux builds I published are done. The one big difference is that Linux 
generally have quite weak guarantees about binary compatibility in 
userspace libs. So building from sources locally with the same gcc/glibc 
all other libs are using is likely will be a way safer (about the things 
like crashes in X11-related code) than using the same sources built with 
an ancient gcc/glibc (that all the "portable" openjdk builds are doing).

-- 
-Alex

**Comment by gouessej** [comment] 2016-04-13 10:58
Would it work under Mageia Linux?

**Comment by alexkasko** [comment] 2016-04-13 11:13
On 04/13/2016 11:58 AM, Julien Gouesse wrote:
> Would it work under Mageia Linux?

Yes, some configuration switches may be required in some cases (like 
--with-boot-jdk or --with-extra-cflags) but generally that 
configure+make method should work on any glibc-based x86_64 Linux.


-- 
-Alex

**Comment by alexkasko** [comment] 2016-04-27 21:22
Small update, jdk8 windows x86_64 is ready to ship (on a github), just waiting for some organizational bits to settle down to publish it. It should appear in a day or two.

**Comment by erickwill** [comment] 2016-04-27 21:28
@alexkasko Thanks for that! :) Looking forward for the linux update too :+1:  :)

**Comment by alexkasko** [comment] 2016-04-29 19:42
jdk8 windows x86_64 binaries published:

 - github repo: https://github.com/ojdkbuild/ojdkbuild
 - first release announce: https://groups.google.com/forum/#!topic/ojdkbuild/WDXg0deZ57Q

The project currently contains little documentation, I hope to improve that situation in some weeks.

Please feel free to write comments and questions to ojdkbuild google group and to ojdkbuild github repo bugtracker.

I am closing this issue, the whole openjdk-unofficial-builds project is discontinued.

**Closed by alexkasko** 2016-04-29 19:42 UTC

**Comment by IceMan81** [comment] 2016-04-30 20:35
@codespotx Do you have 32-bit builds for Windows?

**Comment by djx314** [comment] 2016-05-01 13:57
@codespotx 32-bit +1
